/* GENERATED by scripts/sync-blogs.py — edit markdown in media/documents/reports/posts/, not this file. */
export type BlogPost = {
  slug: string;
  date: string;
  title: string;
  teaser: string;
  brand: "Ava" | "RootMC" | "Root Record" | "Alex";
  paragraphs: string[];
  bullets?: string[];
  after?: string[];
  audio?: string[];
  sources?: string[];
  published?: string;
  categories: string[];
};

export const HOME_BRAND: BlogPost["brand"] = "Alex";
export const PAGE_SIZE = 8;
export const ARCHIVE_REVISED = "2026-08-20 12:04:21 HST";

export const CATEGORIES: { id: string; label: string }[] = [
  { id: "site", label: "Site" },
  { id: "solar", label: "Solar" },
  { id: "media", label: "Media" },
  { id: "ops", label: "Notes" },
];

const MEDIA_FILE = "https://avaivy.cloud/api/media/public/file?path=";

export function mediaUrl(rel: string): string {
  return MEDIA_FILE + encodeURIComponent(rel.replace(/^\/+/, ""));
}

export function formatStamp(p: Pick<BlogPost, "date" | "published">): string {
  if (p.published) {
    const m = p.published.match(/^(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2}:\d{2})(Z|[+-]\d{2}:\d{2})/);
    if (m) {
      const tz = m[3] === "-10:00" ? "HST" : m[3] === "Z" || m[3] === "+00:00" ? "UTC" : m[3];
      return `${m[1]} ${m[2]} ${tz}`;
    }
    return p.published;
  }
  if (p.date.length === 7) return `${p.date} · month precision`;
  return `${p.date} · day precision`;
}

export function datetimeAttr(p: Pick<BlogPost, "date" | "published">): string {
  return p.published || (p.date.length === 7 ? `${p.date}-01` : p.date);
}

export const POSTS: BlogPost[] = [
  {
    slug: "site-foundation",
    date: "2026-08-20",
    title: "alexrs94.site is live — solar, media, and a public blog",
    teaser: "Personal foundation site for Alex: solar ops, media work, YouTube, and dated notes that stay off the three brand blogs.",
    brand: "Alex",
    categories: ["site", "solar"],
    paragraphs: ["alexrs94.site is the personal public home for Alex — separate from Ava Ivy, Root Record, and RootMC. Those three keep product and runtime changelogs. This site is for solar host context, media and flight work, and personal notes."],
    published: "2026-08-20T10:00:00-10:00",
    bullets: ["Home, Solar, and Media pages are the foundation.", "Blog posts live under media/documents/reports/posts/alex and sync into the site.", "YouTube stays at @HIqualityviews.", "Root Record, Ava, and RootMC remain linked from the nav for the wider ecosystem."],
    after: ["More posts will land here as solar ops, media collections, and public builds need a personal channel that is not a brand changelog."],
  }
];

export function getPost(slug: string): BlogPost | undefined {
  return POSTS.find((p) => p.slug === slug);
}

export function neighbors(slug: string): { older?: BlogPost; newer?: BlogPost } {
  const i = POSTS.findIndex((p) => p.slug === slug);
  if (i < 0) return {};
  return {
    newer: i > 0 ? POSTS[i - 1] : undefined,
    older: i + 1 < POSTS.length ? POSTS[i + 1] : undefined,
  };
}
