name = "rootmc-api"
main = "src/rootmc-api/worker.ts"
compatibility_date = "2024-11-01"

routes = [
  { pattern = "rootmc.info/*", zone_name = "rootmc.info" },
  { pattern = "api.rootmc.info/*", zone_name = "rootmc.info" },
]

[[d1_databases]]
binding = "AVA_HEARTBEAT_DB"
database_name = "ava-heartbeat"
database_id = "9991d162-a07f-4931-aa2f-2fbe6edc33c0"

[triggers]
crons = ["* * * * *", "45 8 * * *"]
[[d1_databases]]
binding = "ROOTMC_LIVE_DB"
database_name = "rootmc-live"
database_id = "489b5c16-022f-4533-9cae-0df17aaafd2f"

[[hyperdrive]]
binding = "LIVE_DB"
id = "b243adce0a4c48a39b491612008fcf51"

