/**
 * Allowlisted Ava operator commands for the desktop Terminal page.
 * Only entries here can be spawned from the Electron UI.
 */
export const OPS_COMMAND_GROUPS = [
  {
    id: "reports",
    label: "Reports · issue now / early",
    commands: [
      {
        id: "economy-brief-force",
        label: "Economy Brief (deploy)",
        script: "post-economy-brief.mjs",
        args: ["--force"],
        detail: "Post Economy Brief → Discord #economy-info (RootMC live)",
        confirm: "Deploy Economy Brief to #economy-info now?",
      },
      {
        id: "economy-brief-dry",
        label: "Economy Brief (dry)",
        script: "post-economy-brief.mjs",
        args: ["--dry"],
        detail: "Check 12h watermark / would-post without calling API",
      },
      {
        id: "hour-recap-force",
        label: "Hour recap (force)",
        script: "hour-recap.mjs",
        args: ["--force"],
        detail: "Slack #development-feed hour recap now",
      },
      {
        id: "hour-recap-dry",
        label: "Hour recap (dry)",
        script: "hour-recap.mjs",
        args: ["--force", "--dry"],
        detail: "Build hour recap without posting",
      },
      {
        id: "urgent-tg-force",
        label: "Urgent Telegram (force)",
        script: "urgent-telegram.mjs",
        args: ["--force"],
        detail: "Personal urgent digest to operator TG",
      },
      {
        id: "merged-morning-summary",
        label: "Merged morning summary (force)",
        script: "merged-morning-summary.mjs",
        args: ["--force"],
        detail: "Grok synthesis of 10:00 datapoints → automations + updates",
        confirm: "Post Merged morning Summary Report now?",
      },
      {
        id: "morning-brief",
        label: "Morning brief",
        script: "wave0-morning-brief.mjs",
        args: [],
        detail: "Morning ops brief → TG + Slack + Discord pointer",
        confirm: "Post / re-issue the morning brief now?",
      },
      {
        id: "eod-brief",
        label: "EOD brief",
        script: "wave8-eod.mjs",
        args: [],
        detail: "End-of-day Telegram to operator",
        confirm: "Send the EOD brief now?",
      },
      {
        id: "dump-incremental",
        label: "Channel dump (incremental)",
        script: "dump-channels-incremental.mjs",
        args: [],
        detail: "Incremental channel dump → files + Telegram",
      },
      {
        id: "dump-incremental-seed",
        label: "Channel dump (seed)",
        script: "dump-channels-incremental.mjs",
        args: ["--seed"],
        detail: "Seed / catch-up incremental dump",
      },
      {
        id: "dump-full",
        label: "Channel dump (full)",
        script: "dump-channels-full.mjs",
        args: [],
        detail: "Full channel dump — can be heavy",
        confirm: "Run a full channel dump now?",
      },
      {
        id: "post-catchup-updates",
        label: "Catch-up → #updates",
        script: "post-catchup-updates.mjs",
        args: [],
        detail: "Post catch-up summary to Discord #updates",
        confirm: "Post catch-up summary to #updates?",
      },
      {
        id: "full-update-post",
        label: "Full update post",
        script: "full-update-post.mjs",
        args: [],
        detail: "Full update post",
        confirm: "Issue a full update post?",
      },
      {
        id: "finance-notify",
        label: "Finance review (notify)",
        script: "finance-smoke.mjs",
        args: ["--notify"],
        detail: "Force finance review + Telegram notify",
      },
      {
        id: "finance-smoke",
        label: "Finance smoke",
        script: "finance-smoke.mjs",
        args: [],
        detail: "Stripe snapshot + ops ledger check (no fake player data)",
      },
      {
        id: "morning-rootrestart",
        label: "Morning /rootrestart (prod)",
        script: "morning-rootrestart.mjs",
        args: ["--force"],
        detail: "In-game warnings then /rootrestart on live play.rootmc.net",
        confirm: "Restart LIVE RootMC with warnings now?",
      },
      {
        id: "biz-status",
        label: "Biz / dev hours",
        script: "biz-status.mjs",
        args: [],
        detail: "Alexander + Ava time tracking + per-process CPU",
      },
      {
        id: "biz-clock-in",
        label: "Clock in (Alex)",
        script: "biz-clock.mjs",
        args: ["in"],
        detail: "Start Alexander time entry (Ava uptime stays automatic)",
      },
      {
        id: "biz-clock-out",
        label: "Clock out (Alex)",
        script: "biz-clock.mjs",
        args: ["out"],
        detail: "Close Alexander time entry",
      },
      {
        id: "early-login-now",
        label: "Early login GM (force)",
        script: "early-login-now.mjs",
        args: ["--force"],
        detail: "Good morning · sampling started · reports at 10:00 · merged summary 10:05",
        confirm: "Post early-login good morning to automations now?",
      },
      {
        id: "absolute-ops-today",
        label: "Absolute ops today",
        script: "absolute-ops-today.mjs",
        args: [],
        detail: "Absolute Ops batch + phase catchup",
        confirm: "Run Absolute Ops today batch?",
      },
    ],
  },
  {
    id: "sleep-wake",
    label: "Sleep · wake · good morning",
    commands: [
      {
        id: "wake-catchup",
        label: "Wake + catchup",
        script: "wake-and-catchup.mjs",
        args: [],
        detail: "Clear sleep/hush and run catchup digests",
      },
      {
        id: "gm-now",
        label: "Good morning now",
        script: "post-good-morning-now.mjs",
        args: [],
        detail: "Immediate GM + clear sleep + start Ava",
        confirm: "Post good morning and wake Ava now?",
      },
      {
        id: "queue-gm",
        label: "Queue good morning",
        script: "queue-good-morning.mjs",
        args: [],
        detail: "Queue GM for next boot, then sleep/stop",
      },
      {
        id: "go-to-bed",
        label: "Go to bed",
        script: "go-to-bed.mjs",
        args: [],
        detail: "Soft sleep + Discord bedtime post",
        confirm: "Put Ava to bed (soft sleep)?",
      },
      {
        id: "sleep-ava",
        label: "Sleep until morning",
        script: "sleep-ava.mjs",
        args: [],
        detail: "Soft sleep until ~10:00 HST",
        confirm: "Soft-sleep Ava until morning?",
      },
      {
        id: "night-powerdown",
        label: "Night powerdown blast",
        script: "night-powerdown-blast.mjs",
        args: [],
        detail: "Night gn blast + soft sleep",
        confirm: "Run night powerdown blast?",
      },
      {
        id: "cloud-dark",
        label: "Cloud-dark pause",
        script: "cloud-dark-pause.mjs",
        args: [],
        detail: "Enter cloud-dark + hush mode",
        confirm: "Enable cloud-dark pause?",
      },
    ],
  },
  {
    id: "catchup",
    label: "Catchup · scans",
    commands: [
      {
        id: "phase-catchup",
        label: "Phase catchup",
        script: "phase-catchup.mjs",
        args: [],
        detail: "Force follow-up scan + soft-acks + queues",
      },
      {
        id: "phase-catchup-all",
        label: "Phase catchup (--all)",
        script: "phase-catchup.mjs",
        args: ["--all"],
        detail: "Full phase catchup sweep",
      },
      {
        id: "catchup-unreplied",
        label: "Catchup unreplied",
        script: "catchup-unreplied.mjs",
        args: [],
        detail: "Reply to unreplied Ava mentions",
        confirm: "Reply to unreplied mentions now?",
      },
      {
        id: "cron-catchup",
        label: "Cron catchup",
        script: "ava-core-catchup.mjs",
        args: [],
        detail: "Force offline cron jobs / soft-acks",
        confirm: "Force cron catchup (all catchup jobs)?",
      },
      {
        id: "catchup-standing",
        label: "Catchup standing",
        script: "catchup-standing.mjs",
        args: [],
        detail: "Standing catchup posts",
      },
      {
        id: "catchup-snappy",
        label: "Catchup snappy",
        script: "catchup-snappy.mjs",
        args: [],
        detail: "Snappy catchup posts",
      },
      {
        id: "dm-operator-catchup",
        label: "DM operator catchup",
        script: "dm-operator-catchup-home.mjs",
        args: [],
        detail: "Discord DM catchup home to Alex",
        confirm: "DM operator catchup home?",
      },
      {
        id: "full-channel-scan",
        label: "Full channel scan",
        script: "full-channel-scan.mjs",
        args: [],
        detail: "Full channel scan",
        confirm: "Run full channel scan?",
      },
    ],
  },
  {
    id: "lifecycle",
    label: "Lifecycle · presence",
    commands: [
      {
        id: "restart-ava",
        label: "Restart Ava",
        script: "restart-ava.mjs",
        args: [],
        detail: "Silent self-restart / upgrade path",
        confirm: "Restart Ava now?",
      },
      {
        id: "rich-presence",
        label: "Rich presence",
        script: "rich-presence.mjs",
        args: [],
        detail: "Discord rich presence once",
      },
      {
        id: "ensure-deps",
        label: "Ensure deps",
        script: "ensure-deps.mjs",
        args: [],
        detail: "Check / install core dependencies",
      },
      {
        id: "http-restart",
        label: "HTTP /api/restart",
        kind: "http",
        method: "POST",
        path: "/api/restart",
        detail: "POST selected brain /api/restart",
        confirm: "POST /api/restart to local Ava?",
      },
      {
        id: "http-upgrade",
        label: "HTTP /api/upgrade",
        kind: "http",
        method: "POST",
        path: "/api/upgrade",
        detail: "POST selected brain /api/upgrade",
        confirm: "POST /api/upgrade to local Ava?",
      },
      {
        id: "http-health",
        label: "HTTP /health",
        kind: "http",
        method: "GET",
        path: "/health",
        detail: "GET selected brain /health",
      },
      {
        id: "http-status",
        label: "HTTP /api/status",
        kind: "http",
        method: "GET",
        path: "/api/status",
        detail: "GET selected brain /api/status snapshot",
      },
    ],
  },
  {
    id: "cleanup",
    label: "Cleanup · scrub (confirm)",
    commands: [
      {
        id: "purge-junk",
        label: "Purge junk Ava",
        script: "purge-junk-ava.mjs",
        args: [],
        detail: "Purge junk Ava posts",
        confirm: "Purge junk Ava messages?",
      },
      {
        id: "purge-dark-spam",
        label: "Purge dark spam",
        script: "purge-dark-spam.mjs",
        args: [],
        detail: "Purge dark-mode spam",
        confirm: "Purge dark spam?",
      },
      {
        id: "silent-close-props",
        label: "Silent close props",
        script: "silent-close-props.mjs",
        args: [],
        detail: "Silently close stale proposals",
        confirm: "Silent-close proposals?",
      },
      {
        id: "scrub-manipulation",
        label: "Scrub manipulation mentions",
        script: "scrub-manipulation-gate-mentions.mjs",
        args: [],
        detail: "Scrub manipulation-gate mentions",
        confirm: "Run scrub?",
      },
    ],
  },
  {
    id: "data",
    label: "Data · mirrors",
    commands: [
      {
        id: "d1-export",
        label: "D1 export → local",
        script: "d1-export-to-local.mjs",
        args: [],
        detail: "Export D1 to local files",
        confirm: "Run D1 export?",
      },
      {
        id: "d1-full-sync",
        label: "D1 full sync",
        script: "d1-full-sync-to-ava.mjs",
        args: [],
        detail: "Full D1 sync into Ava",
        confirm: "Run full D1 sync?",
      },
      {
        id: "harvest-reactions",
        label: "Harvest reactions",
        script: "harvest-reactions.mjs",
        args: [],
        detail: "Harvest Discord reactions",
      },
      {
        id: "log-query",
        label: "Log query (help)",
        script: "log-query.mjs",
        args: ["--help"],
        detail: "Show log-query CLI help",
      },
    ],
  },
  {
    id: "danger",
    label: "Danger zone",
    commands: [
      {
        id: "disable-cf-crons",
        label: "Disable CF crons",
        script: "disable-cf-crons.mjs",
        args: [],
        detail: "Empty Cloudflare Worker crons",
        confirm: "Disable Cloudflare crons? This is disruptive.",
      },
      {
        id: "undeploy-api-workers",
        label: "Undeploy API workers",
        script: "undeploy-api-workers.mjs",
        args: [],
        detail: "Soft-ack complete then delete Workers",
        confirm: "UNDEPLOY API workers? Only if you really mean it.",
      },
    ],
  },
];

/** Flat map id → command */
export function opsCommandById(id) {
  for (const g of OPS_COMMAND_GROUPS) {
    for (const c of g.commands) {
      if (c.id === id) return c;
    }
  }
  return null;
}

export function listOpsCatalog() {
  return OPS_COMMAND_GROUPS.map((g) => ({
    id: g.id,
    label: g.label,
    commands: g.commands.map((c) => ({
      id: c.id,
      label: c.label,
      detail: c.detail || "",
      confirm: c.confirm || null,
      kind: c.kind || "script",
    })),
  }));
}
