const ORDER=['Primary','security','Backup'];
const COLORS={Primary:'#75a8ff',security:'#b39cff',Backup:'#68e09b'};
const $=s=>document.querySelector(s);
const fmt=(n,d=1)=>n==null||Number.isNaN(Number(n))?'—':Number(n).toFixed(d);
const kw=n=>n==null?'—':Math.abs(n)>=1000?`${(n/1000).toFixed(2)} kW`:`${fmt(n,0)} W`;
let charts={};let hours=12;let timer;
function destroyCharts(){Object.values(charts).forEach(c=>c?.destroy());charts={}}
function setStatus(ok,msg){$('#statusDot').style.color=ok?'#68e09b':'#ff7777';$('#statusDot').style.background=ok?'#68e09b':'#ff7777';$('#statusText').textContent=msg}
function metric(label,value,unit,note=''){return `<div class="metric"><div class="label">${label}</div><div class="value">${value}<span class="unit">${unit}</span></div><div class="note">${note}</div></div>`}
function buildRollup(rows,live){let socs=[],tin=0,tout=0,solar=0,ein=0,eout=0,online=0;rows.forEach(r=>{if(r.soc_avg!=null)socs.push(r.soc_avg);tin+=r.in_w_avg||0;tout+=r.out_w_avg||0;solar+=r.solar_w_avg||0;ein+=r.energy_in_wh||0;eout+=r.energy_out_wh||0;online+=r.online_pct||0});const soc=socs.length?socs.reduce((a,b)=>a+b,0)/socs.length:null;const onlinePct=rows.length?online/rows.length:null;const net=tin-tout;$('#rollup').innerHTML=[metric('System SOC',fmt(soc,1),' %','average across banks'),metric('Power In',kw(tin),'','current aggregate'),metric('Power Out',kw(tout),'','current aggregate'),metric('Net Power',kw(net),'',net>=0?'charging / surplus':'discharging / load'),metric('Solar',kw(solar),'','reported solar input'),metric('Online',fmt(onlinePct,0),' %','minute sample availability'),metric('Energy In',fmt(ein/1000,3),' kWh','selected latest minute windows'),metric('Energy Out',fmt(eout/1000,3),' kWh','selected latest minute windows')].join('')}
function buildLive(live){const el=$('#liveLegend');el.innerHTML=(live||[]).map(r=>`<span><i style="background:${COLORS[r.name]||'#8792a5'}"></i>${r.name||r.sn}</span>`).join('')}
function buildFlow(rows,live){const by={};rows.forEach(r=>by[r.name]=r);const current=live||[];let totalOut=current.reduce((a,r)=>a+(r.out_w||0),0),totalIn=current.reduce((a,r)=>a+(r.in_w||0),0),totalSolar=current.reduce((a,r)=>a+(r.solar_w||0),0);const socs=rows.filter(r=>r.soc_avg!=null).map(r=>r.soc_avg);const soc=socs.length?socs.reduce((a,b)=>a+b,0)/socs.length:0;const pct=Math.max(0,Math.min(100,soc));const nodes=ORDER.map(n=>{const r=by[n]||{};return `<div class="node"><div class="name">${n}</div><div class="small">${r.online_pct>=50?'ONLINE':'OFFLINE'} · SOC ${fmt(r.soc_avg,1)}%</div><div class="power">${kw(r.out_w_avg||0)}</div><div class="small">output · in ${kw(r.in_w_avg||0)} · solar ${kw(r.solar_w_avg||0)}</div></div>`}).join('');$('#flow').innerHTML=`<div class="flow"><div class="flow-col"><div class="node"><div class="name">Solar / external input</div><div class="power">${kw(totalSolar)}</div><div class="small">reported solar input</div></div><div class="arrow">↓</div><div class="node"><div class="name">Other input</div><div class="power">${kw(Math.max(0,totalIn-totalSolar))}</div><div class="small">non-solar reported input</div></div></div><div class="flow-center"><div class="battery-ring" style="--pct:${pct}%"><div class="inside"><div class="soc">${fmt(soc,1)}%</div><div class="caption">SYSTEM SOC</div><div class="small">${kw(totalIn)} in · ${kw(totalOut)} out</div></div></div></div><div class="flow-col">${nodes}<div class="node"><div class="name">System load</div><div class="power">${kw(totalOut)}</div><div class="small">aggregate device output</div></div></div></div>`}
function buildDevices(rows,live){const liveBy={};(live||[]).forEach(r=>liveBy[r.name]=r);$('#devices').innerHTML=ORDER.map(n=>{const r=rows.find(x=>x.name===n);const l=liveBy[n]||{};if(!r)return `<article class="device"><div class="empty">${n}: waiting for analytics</div></article>`;const trend=r.trend||'stable';return `<article class="device"><div class="device-head"><div><div class="eyebrow">ENERGY BANK</div><div class="device-name">${n}</div></div><div class="${l.online?'online':'offline'}">● ${l.online?'ONLINE':'OFFLINE'}</div></div><div class="soc-row"><div class="soc-value">${fmt(r.soc_avg,1)}<small>%</small></div><div class="subtle">Δ ${fmt(r.soc_delta,2)} · ${trend}</div></div><div class="bar"><span style="width:${Math.max(0,Math.min(100,r.soc_avg||0))}%"></span></div><div class="device-stats"><div class="stat"><label>Live input</label><b>${kw(l.in_w)}</b></div><div class="stat"><label>Live output</label><b>${kw(l.out_w)}</b></div><div class="stat"><label>Avg input</label><b>${kw(r.in_w_avg)}</b></div><div class="stat"><label>Avg output</label><b>${kw(r.out_w_avg)}</b></div><div class="stat"><label>Solar</label><b>${kw(r.solar_w_avg)}</b></div><div class="stat"><label>Net</label><b>${kw(r.net_w_avg)}</b></div><div class="stat"><label>Energy in</label><b>${fmt(r.energy_in_wh,2)} Wh</b></div><div class="stat"><label>Energy out</label><b>${fmt(r.energy_out_wh,2)} Wh</b></div><div class="stat"><label>SOC min / max</label><b>${fmt(r.soc_min,1)} / ${fmt(r.soc_max,1)}%</b></div><div class="stat"><label>SOC stdev</label><b>${fmt(r.soc_stdev,2)}%</b></div><div class="stat"><label>Online</label><b>${fmt(r.online_pct,1)}%</b></div><div class="stat"><label>Samples</label><b>${r.samples??'—'}</b></div></div></article>`}).join('')}
function buildTable(rows){$('#statsTable').innerHTML=rows.map(r=>`<tr><td><b>${r.name}</b></td><td>${fmt(r.soc_avg,1)}%</td><td>${fmt(r.soc_min,1)}–${fmt(r.soc_max,1)}%</td><td>${fmt(r.soc_delta,2)}</td><td>${kw(r.in_w_avg)}</td><td>${kw(r.out_w_avg)}</td><td>${kw(r.solar_w_avg)}</td><td>${kw(r.net_w_avg)}</td><td>${fmt(r.energy_in_wh,2)} Wh</td><td>${fmt(r.energy_out_wh,2)} Wh</td><td>${fmt(r.online_pct,1)}%</td><td class="trend-${r.trend}">${r.trend||'—'}</td></tr>`).join('')||'<tr><td colspan="12">No analytics yet.</td></tr>'}
function buildDetails(rows,live){const lb={};(live||[]).forEach(r=>lb[r.name]=r);$('#details').innerHTML=rows.map(r=>{const l=lb[r.name]||{};return `<article class="detail"><h3>${r.name}</h3><div class="kv"><span>Serial</span><b>${r.sn||'—'}</b></div><div class="kv"><span>Last live timestamp</span><b>${l.ts?new Date(l.ts).toLocaleTimeString():'—'}</b></div><div class="kv"><span>Live SOC</span><b>${fmt(l.soc,1)}%</b></div><div class="kv"><span>Live input</span><b>${kw(l.in_w)}</b></div><div class="kv"><span>Live output</span><b>${kw(l.out_w)}</b></div><div class="kv"><span>Live solar</span><b>${kw(l.solar_w)}</b></div><div class="kv"><span>Input min / max</span><b>${kw(r.in_w_min)} / ${kw(r.in_w_max)}</b></div><div class="kv"><span>Output min / max</span><b>${kw(r.out_w_min)} / ${kw(r.out_w_max)}</b></div><div class="kv"><span>Input delta</span><b>${kw(r.in_w_delta)}</b></div><div class="kv"><span>Output delta</span><b>${kw(r.out_w_delta)}</b></div><div class="kv"><span>Load ratio</span><b>${fmt(r.load_ratio,3)}</b></div></article>`}).join('')}
function chartOptions(){return{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{labels:{color:'#8792a5',boxWidth:10,font:{size:10}}},tooltip:{backgroundColor:'#101722',borderColor:'#2a3547',borderWidth:1}},scales:{x:{ticks:{color:'#667287',maxTicksLimit:12,font:{size:9}},grid:{color:'#18202c'}},y:{ticks:{color:'#667287',font:{size:9}},grid:{color:'#18202c'}}}}}
function datasets(rows,field){const labels=[...new Set(rows.map(r=>r.minute_key))].sort();return {labels,datasets:ORDER.map(n=>({label:n,data:labels.map(l=>{const r=rows.find(x=>x.name===n&&x.minute_key===l);return r?.[field]??null}),borderColor:COLORS[n],backgroundColor:'transparent',pointRadius:0,borderWidth:2,tension:.28}))}}
function dual(rows,a,b){const labels=[...new Set(rows.map(r=>r.minute_key))].sort();return {labels,datasets:ORDER.flatMap(n=>[{label:`${n} in`,data:labels.map(l=>{const r=rows.find(x=>x.name===n&&x.minute_key===l);return r?.[a]??null}),borderColor:COLORS[n],pointRadius:0,borderWidth:2,tension:.28},{label:`${n} out`,data:labels.map(l=>{const r=rows.find(x=>x.name===n&&x.minute_key===l);return r?.[b]??null}),borderColor:COLORS[n],borderDash:[6,4],pointRadius:0,borderWidth:1.5,tension:.28}])}}
function buildCharts(rows){destroyCharts();const o=chartOptions();charts.soc=new Chart($('#socChart'),{type:'line',data:datasets(rows,'soc_avg'),options:o});charts.power=new Chart($('#powerChart'),{type:'line',data:dual(rows,'in_w_avg','out_w_avg'),options:o});charts.solar=new Chart($('#solarChart'),{type:'line',data:datasets(rows,'solar_w_avg'),options:o});charts.net=new Chart($('#netChart'),{type:'line',data:datasets(rows,'net_w_avg'),options:o})}
async function load(){try{const [now,hist]=await Promise.all([fetch('/system/api/now',{cache:'no-store'}).then(r=>r.json()),fetch(`/system/api/history?hours=${hours}`,{cache:'no-store'}).then(r=>r.json())]);const rows=now.enhanced||[];buildRollup(rows,now.live);buildLive(now.live);buildFlow(rows,now.live);buildDevices(rows,now.live);buildTable(rows);buildDetails(rows,now.live);buildCharts(hist.rows||[]);const ts=now.ts||new Date().toISOString();$('#clock').textContent=new Date(ts).toLocaleString();$('#lastUpdated').textContent=`Updated ${new Date(ts).toLocaleTimeString()}`;setStatus(true,'SYSTEM ONLINE')}catch(e){console.error(e);setStatus(false,'DATA OFFLINE');$('#lastUpdated').textContent='Unable to load energy data'}}
$('#refreshBtn').addEventListener('click',load);document.querySelectorAll('#range button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#range button').forEach(x=>x.classList.remove('active'));b.classList.add('active');hours=Number(b.dataset.hours);load()}));load();timer=setInterval(load,15000);
